version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: crawler
    ports:
      - 37017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local